### ISSUE TITLE
jobs.physicals isn't capped by default

### ISSUE THREAD

**Issue by FedeG** [lelylan/physicals#8]
Code: [Link](https://github.com/lelylan/physicals/blob/master/lib/logic.coffee#L13)

**Comment by andreareginato** [comment]
Isn't this the needed [capped collection config](https://github.com/lelylan/physicals/blob/master/app/models/jobs/physical.coffee#L10)?

**Comment by FedeG** [comment]
@andreareginato.
Yes, this is the needed configuration but this configuration isn't in all microservices that use capped collections.
If you run physicals microservices first, the collection is capped.
If you run physicals microservices after, the collection not is capped.
